
const planetImages: Record<string, any[]> = {
  mercury: [
    require('../../assets/wakusei_2/mercury/img_1.jpg'),
    require('../../assets/wakusei_2/mercury/img_2.jpg'),
    require('../../assets/wakusei_2/mercury/img_3.jpg'),
    require('../../assets/wakusei_2/mercury/img_4.jpg'),
    require('../../assets/wakusei_2/mercury/img_5.jpg'),
    require('../../assets/wakusei_2/mercury/img_6.jpg'),
    require('../../assets/wakusei_2/mercury/img_7.jpg'),
    require('../../assets/wakusei_2/mercury/img_8.jpg'),
    require('../../assets/wakusei_2/mercury/img_9.jpg'),
    require('../../assets/wakusei_2/mercury/img_10.jpg'),
  ],
  venus: [
    require('../../assets/wakusei_2/venus/img_1.jpg'),
    require('../../assets/wakusei_2/venus/img_2.jpg'),
    require('../../assets/wakusei_2/venus/img_3.jpg'),
    require('../../assets/wakusei_2/venus/img_4.jpg'),
    require('../../assets/wakusei_2/venus/img_5.jpg'),
    require('../../assets/wakusei_2/venus/img_6.jpg'),
    require('../../assets/wakusei_2/venus/img_7.jpg'),
    require('../../assets/wakusei_2/venus/img_8.jpg'),
    require('../../assets/wakusei_2/venus/img_9.jpg'),
    require('../../assets/wakusei_2/venus/img_10.jpg'),
  ],
  earth: [
    require('../../assets/wakusei_2/earth/img_1.jpg'),
    require('../../assets/wakusei_2/earth/img_2.jpg'),
    require('../../assets/wakusei_2/earth/img_3.jpg'),
    require('../../assets/wakusei_2/earth/img_4.jpg'),
    require('../../assets/wakusei_2/earth/img_5.jpg'),
    require('../../assets/wakusei_2/earth/img_6.jpg'),
    require('../../assets/wakusei_2/earth/img_7.jpg'),
    require('../../assets/wakusei_2/earth/img_8.jpg'),
    require('../../assets/wakusei_2/earth/img_9.jpg'),
    require('../../assets/wakusei_2/earth/img_10.jpg'),
  ],
  mars: [
    require('../../assets/wakusei_2/mars/img_1.jpg'),
    require('../../assets/wakusei_2/mars/img_2.jpg'),
    require('../../assets/wakusei_2/mars/img_3.jpg'),
    require('../../assets/wakusei_2/mars/img_4.jpg'),
    require('../../assets/wakusei_2/mars/img_5.jpg'),
    require('../../assets/wakusei_2/mars/img_6.jpg'),
    require('../../assets/wakusei_2/mars/img_7.jpg'),
    require('../../assets/wakusei_2/mars/img_8.jpg'),
    require('../../assets/wakusei_2/mars/img_9.jpg'),
    require('../../assets/wakusei_2/mars/img_10.jpg'),
  ],
  jupiter: [
    require('../../assets/wakusei_2/jupiter/img_1.jpg'),
    require('../../assets/wakusei_2/jupiter/img_2.jpg'),
    require('../../assets/wakusei_2/jupiter/img_3.jpg'),
    require('../../assets/wakusei_2/jupiter/img_4.jpg'),
    require('../../assets/wakusei_2/jupiter/img_5.jpg'),
    require('../../assets/wakusei_2/jupiter/img_6.jpg'),
    require('../../assets/wakusei_2/jupiter/img_7.jpg'),
    require('../../assets/wakusei_2/jupiter/img_8.jpg'),
    require('../../assets/wakusei_2/jupiter/img_9.jpg'),
    require('../../assets/wakusei_2/jupiter/img_10.jpg'),
  ],
  saturn: [
    require('../../assets/wakusei_2/saturn/img_1.jpg'),
    require('../../assets/wakusei_2/saturn/img_2.jpg'),
    require('../../assets/wakusei_2/saturn/img_3.jpg'),
    require('../../assets/wakusei_2/saturn/img_4.jpg'),
    require('../../assets/wakusei_2/saturn/img_5.jpg'),
    require('../../assets/wakusei_2/saturn/img_6.jpg'),
    require('../../assets/wakusei_2/saturn/img_7.jpg'),
    require('../../assets/wakusei_2/saturn/img_8.jpg'),
    require('../../assets/wakusei_2/saturn/img_9.jpg'),
    require('../../assets/wakusei_2/saturn/img_10.jpg'),
  ],
  uranus: [
    require('../../assets/wakusei_2/uranus/img_1.jpg'),
    require('../../assets/wakusei_2/uranus/img_2.jpg'),
    require('../../assets/wakusei_2/uranus/img_3.jpg'),
    require('../../assets/wakusei_2/uranus/img_4.jpg'),
    require('../../assets/wakusei_2/uranus/img_5.jpg'),
    require('../../assets/wakusei_2/uranus/img_6.jpg'),
    require('../../assets/wakusei_2/uranus/img_7.jpg'),
    require('../../assets/wakusei_2/uranus/img_8.jpg'),
    require('../../assets/wakusei_2/uranus/img_9.jpg'),
    require('../../assets/wakusei_2/uranus/img_10.jpg'),
  ],
  neptune: [
    require('../../assets/wakusei_2/neptune/img_1.jpg'),
    require('../../assets/wakusei_2/neptune/img_2.jpg'),
    require('../../assets/wakusei_2/neptune/img_3.jpg'),
    require('../../assets/wakusei_2/neptune/img_4.jpg'),
    require('../../assets/wakusei_2/neptune/img_5.jpg'),
    require('../../assets/wakusei_2/neptune/img_6.jpg'),
    require('../../assets/wakusei_2/neptune/img_7.jpg'),
    require('../../assets/wakusei_2/neptune/img_8.jpg'),
    require('../../assets/wakusei_2/neptune/img_9.jpg'),
    require('../../assets/wakusei_2/neptune/img_10.jpg'),
  ],
};

export default planetImages;
